### ISSUE TITLE
TypeError in afterEach when test has no output at all

### ISSUE THREAD

**Issue by tripodsan** [AleG94/mocha-suppress-logs#12]
**problem**
I have a test with no output, then I get the following error:

```
TypeError: Cannot read properties of undefined (reading 'stream')
    at Context.afterEach (node_modules/mocha-suppress-logs/index.js:14:29)
    at process.processImmediate (node:internal/timers:476:21)
```

**workaround**
add `process.stdout.write('')`

**note**
I'm running the tests within webstorm, and they set their own reporter:

```
--reporter /Users/shared/Library/Application Support/JetBrains/Toolbox/apps/WebStorm/ch-0/232.10203.14/WebStorm.app/Contents/plugins/nodeJS/js/mocha-intellij/lib/mochaIntellijReporter.js
```

I assume they don't write anything to stdout.

**Comment by tripodsan** [comment]
here a debugging session:

![image](https://github.com/AleG94/mocha-suppress-logs/assets/917628/3654421a-ea23-4ab1-82ea-542751917e23)

**Comment by dominique-pfister** [comment]
Can also be reproduced by using the `min` builtin mocha reporter for some test that produces no output.

**Comment by drewjohnston-0000** [comment]
I have also noticed it to be an issue when using mocha-junit-reporter (no problems with 0.3.1) same error as above gets written to the junit output file

**Comment by tripodsan** [comment]
workaround add a setup hook:

**package.json**
```
....
  "mocha": {
    "require": [
      "test/setup-env.js",
    ],
  },
...
```  

**test/setup-env.js**
```
export const mochaHooks = {
  beforeEach() {
    process.stderr.write('');
  },
};
```
